
DISABLE_AUTO_UPDATE="true"
export ZSH=$HOME/.oh-my-zsh
export PATH="$HOME/bin:$PATH";
export ZSH_THEME="sorin"
plugins=(git brew node docker npm yarn zsh-better-npm-completion docker-compose)
source $ZSH/oh-my-zsh.sh
source $HOME/.aliases
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export FZF_DEFAULT_COMMAND='fd --type f'
export PATH=/Users/nicolasmarien/.deno/bin:$PATH
